spring:
  application:
    name: StudentManagementSystem


  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect